### ISSUE TITLE
something went wrong with logo

### ISSUE THREAD

**Issue by matkoniecz** [tomalrussell/colouring-london#1411]
![screen01](https://github.com/user-attachments/assets/1f91dee9-b369-4af8-9a0d-eb1921433423)
not sure why it was not caught in my earlier tests?

**Comment by matkoniecz** [comment]
It looks like longer text caused box to become wider and failing out of their lines.

Forcing them with `  max-width: 107px;` works but obviously it is not a solution.

**Comment by matkoniecz** [comment]
`font-size: .8em;` in `.category-title` is a bit more proper hack but... Still a hack.

**Comment by mdsimpson42** [comment]
This did happen when we originally changed the category names, but I tested it at a range of Zoom levels on my local machine and on Staging... The little logo at the top and in the key was getting stretched, which I fixed. 

I just tried it now, locally, on staging and on production and I can't replicate.
Does it happen at particular zoom levels or resolutions?

**Comment by mdsimpson42** [comment]
Or in a particular browser?

**Comment by matkoniecz** [comment]
>  not sure why it was not caught in my earlier tests?

That is because for `body` following definition is new, and replaced older: `font-family: var(--bs-font-sans-serif);`

> I just tried it now, locally, on staging and on production and I can't replicate.

note that production has additional change reducing text size

> Does it happen at particular zoom levels or resolutions?

100%, 1920 x 1200 px

> Or in a particular browser?

Firefox 130.0.1 (64-bit)

**Comment by matkoniecz** [comment]
problem disappears on heavy zooming

it appears to be reliably triggered by editing labels, say with inspector to have oversized text length:

 
![screen09](https://github.com/user-attachments/assets/6e75dd85-93bc-4afa-a6c1-68a88273899f)

**Comment by matkoniecz** [comment]
```
.category-title {
	display: block;
	text-align: center;
	font-size: .9em;
	margin: 0;
	padding: .6em;
}
```

removing `	padding: .6em;` reduces problem and text looks fine

![screen02](https://github.com/user-attachments/assets/798c7174-9cf4-4a03-9af7-011d00558e26)
![screen01](https://github.com/user-attachments/assets/221c5ba5-c7d6-4da9-8b4b-c238121c0a76)

still, Age & history looks better with larger padding

And it still does not eliminate root cause.


Adding soft hyphens sort-of works but may result in splitting words where it is not really needed.

![screen03](https://github.com/user-attachments/assets/dbbf826a-c25e-488e-af4c-7a592203a88c)

**Comment by mdsimpson42** [comment]
Yeah, it's a tricky one. The padding was to try and make it look nice, Polly wanted, for example, Age & History not to appear all in one line, as it does on the second picture. I think she wanted the "&" in Typology and size would be on the next line too. I was just trying to do something that doesn't require too much additional code or adding custom code for each category...
